### ISSUE TITLE
Request size issue?

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/fn-village-finder#3]
@onlyjsmith When running with the following request on `fn-village-finder`, OpenFaas seems to just keep running. When running locally on my machine, it takes about 2 mins.

```
{
  "Max_Number_Of_People_In_Cluster": 5000,
  "Min_Number_Of_People_In_Cluster": 100,
  "Maximum_Area_Size_Of_Cluster_Km2": 100,
  "User_Input_Villages_DF": [],
  "filename_raster_pop": {
    "filename": "PHL_worldpop_2015_ppp",
    "url": "https://www.dropbox.com/s/xdphrf9z8w7v4a7/PHL_worldpop_2015_ppp.RData?dl=1"
  }
}
```

On the logs, it seems to start `forking process` and then a minute later it says `Killing process: Rscript main.R`. Then it keeps repeating that cycle...

**Comment by HughSt** [comment]
OK, guess it was just a timeout issue. I changed the `stack.yml` parameters to the following:

```
exec_timeout: 600
write_timeout: 700
read_timeout: 700
```

And it works. Leaving at 10 min timeout for the moment unless anyone has any issues/suggestions...

**Comment by onlyjsmith** [comment]
Short reply: This is a good solution. 

Longer reply: We probably need to have a project-wide policy on timeouts (started this discussion on recent team call). Timeouts are set on both the _function_ and _gateway_. At the moment the gateway timeout is set ~15 mins. We've got an open card on our side to investigate how they inter-relate: i.e. what happens if gateway timeout reached before function timeout, what kind of error messages do we get, etc.

**Comment by onlyjsmith** [comment]
Relates to https://github.com/disarm-platform/algorithms-issues/issues/5

We might do better having platform-wide _deployment-time_ setting of timeouts, rather than relying on each function's `stack.yml`
